//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeList
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public string PartName { get; set; }
        public string Handside { get; set; }
        public string PartNumber { get; set; }
        public string PartCode { get; set; }
        public string ModelCode { get; set; }
        public string DerivationCode { get; set; }
        public string LineNumber { get; set; }
        public string CountryNumber { get; set; }
    }
}
