//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line2_Data
    {
        public long ID { get; set; }
        public Nullable<long> SEQNo { get; set; }
        public string MODEL { get; set; }
        public string VARIENT { get; set; }
        public string FINALBARCODE { get; set; }
        public string SCAN_DATA { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string STATUS { get; set; }
    }
}
