//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line3_Data
    {
        public long Id { get; set; }
        public Nullable<long> SequenceNo { get; set; }
        public string Model { get; set; }
        public string Variant { get; set; }
        public string Shift { get; set; }
        public string FinalQRCode { get; set; }
        public Nullable<System.DateTime> FinalQR_DateTime { get; set; }
        public string Status { get; set; }
    }
}
