//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BarcodeList> BarcodeLists { get; set; }
        public virtual DbSet<Line2_Data> Line2_Data { get; set; }
        public virtual DbSet<Line3_Data> Line3_Data { get; set; }
        public virtual DbSet<OperatorWorkTime> OperatorWorkTimes { get; set; }
        public virtual DbSet<ServerVariable> ServerVariables { get; set; }
        public virtual DbSet<ShiftInfo> ShiftInfoes { get; set; }
        public virtual DbSet<SideBraketLineData> SideBraketLineDatas { get; set; }
        public virtual DbSet<StationInfo> StationInfoes { get; set; }
        public virtual DbSet<TaskInfo> TaskInfoes { get; set; }
        public virtual DbSet<TILTCOM_LineData> TILTCOM_LineData { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<YFG_PowerLineData> YFG_PowerLineData { get; set; }
    }
}
