//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SideBraketLineData
    {
        public long ID { get; set; }
        public Nullable<long> SequenceNo { get; set; }
        public string Model { get; set; }
        public string Varient { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Station { get; set; }
        public string FinalQRCode { get; set; }
        public Nullable<System.DateTime> FinalQRDateTime { get; set; }
        public string InnerCell_ScanData { get; set; }
        public string InnerCell_Status { get; set; }
        public Nullable<System.DateTime> InnerCell_DateTime { get; set; }
        public string OuterCellScanData { get; set; }
        public string OuterCell_Status { get; set; }
        public Nullable<System.DateTime> OuterCell_DateTime1 { get; set; }
        public string Bush_Assy_scanData { get; set; }
        public string Bush_Assy_Status { get; set; }
        public Nullable<System.DateTime> Bush_Assy_DateTime { get; set; }
    }
}
