//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationInfo
    {
        public int ID { get; set; }
        public string StationDesc { get; set; }
        public string StationName { get; set; }
        public string PLC { get; set; }
        public string Printer { get; set; }
        public string CycleRunningBitAddrs { get; set; }
        public string PartOK_BitAdrdrs { get; set; }
        public string PartNG_BitAdrdrs { get; set; }
        public string CycleTimeBitAddrs { get; set; }
        public string CycleCompleteBitAddrs { get; set; }
        public string ScanBitAddrs { get; set; }
        public string TorqueDataReg { get; set; }
        public string ResetBitAddrs { get; set; }
        public string TorqueStatusBitAdrrs { get; set; }
    }
}
