//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TILTCOM_LineData
    {
        public long ID { get; set; }
        public Nullable<long> SequenceNo { get; set; }
        public string Model { get; set; }
        public string Varient { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Station { get; set; }
        public string FinalQRCode { get; set; }
        public Nullable<System.DateTime> FinalQRDateTime { get; set; }
        public string FinalStatus { get; set; }
    }
}
