//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class YFG_PowerLineData
    {
        public long ID { get; set; }
        public Nullable<long> SequenceNo { get; set; }
        public string Model { get; set; }
        public string Varient { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> Station { get; set; }
        public string FinalQRCode { get; set; }
        public Nullable<System.DateTime> FinalQRDateTime { get; set; }
        public string BuiltTkt { get; set; }
        public Nullable<System.DateTime> BuiltTktDateTime { get; set; }
        public string UpperBktClinchingStatus { get; set; }
        public Nullable<System.DateTime> UpperBktClinchingDateTime { get; set; }
        public string UpperGearBoxToq_Ang { get; set; }
        public string UpperGearBoxStatus { get; set; }
        public Nullable<System.DateTime> UpperGearBoxDateTime { get; set; }
        public string UpperLowerFittingStatus { get; set; }
        public Nullable<System.DateTime> UpperLowerFittingDateTime { get; set; }
        public string LowerScrewToq_Ang1 { get; set; }
        public string LowerScrewToq_Ang2 { get; set; }
        public string LowerScrewStatus { get; set; }
        public Nullable<System.DateTime> LowerScrewDateTime { get; set; }
        public string Front_To_RearForceMax { get; set; }
        public string Front_To_RearForceMin { get; set; }
        public string Rear_To_FrontForceMax { get; set; }
        public string Rear_To_FrontForceMin { get; set; }
        public string Rear_To_FrontForceAvg { get; set; }
        public string Front_To_RearForceAvg { get; set; }
        public string SlideForceStatus { get; set; }
        public Nullable<System.DateTime> SlideForceDateTime { get; set; }
        public string LowerBoltToq1 { get; set; }
        public string LowerBoltToq2 { get; set; }
        public string LowerBoltStatus { get; set; }
        public Nullable<System.DateTime> LowerBoltDateTime { get; set; }
        public string RailGearBoxToq_Ang { get; set; }
        public string RailGearBoxStatus { get; set; }
        public Nullable<System.DateTime> RailGearBoxDateTime { get; set; }
        public string RailQA_FR_MaxToq { get; set; }
        public string RailQA_FR_MinToq { get; set; }
        public string RailQA_FR_Dist { get; set; }
        public string RailQA_RF_MaxToq { get; set; }
        public string RailQA_RF_MinToq { get; set; }
        public string RailQA_RF_Dist { get; set; }
        public string RailQA_Status { get; set; }
        public Nullable<System.DateTime> RailQA_DateTime { get; set; }
        public Nullable<System.DateTime> RailVisualInspectionDateTime { get; set; }
        public string FinalStatus { get; set; }
    }
}
